AllCops:
  TargetRubyVersion: 2.0

Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact
